###Recuperar todas las películas
GET http://localhost:1234/movies

###Recuperar una película por id
GET http://localhost:1234/movies/6a360a18-c645-4b47-9a7b-2a71babbf3e0

###Recuperar todas las película por un género
GET http://localhost:1234/movies?genre=drama

### Crear una película con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "El padrino",
    "year": 1994.5,
    "director": "Tarantino",
    "duration": 120,
    "poster": "https://i.pinimg.com/originals/7e/37/b9/7e37b994b613e94cba64f307b1983e39.jpg",
    "genre": ["Crime", "Drama"],
    "rate": 7.7
}

### Actualizar una película con PATCH
PATCH http://localhost:1234/movies/6a360a18-c645-4b47-9a7b-2a71babbf3e0
Content-Type: application/json

{
    "title": "Avatar 123"
}

